language: java
sudo: false
dist: trusty
script: mvn clean install -DRAPIDOID_CI=true

jdk:
  - oraclejdk8

before_install:
  - export MAVEN_OPTS="-Xmx2g $MAVEN_OPTS"
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

install: true

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - JAVA_OPTS="-Xmx2g"
